### PR TITLE
Add more rest methods for nuggets

### PR DESCRIPTION
**Pull request by karkum**
@nathanwchan @aswath87 

I've added PUT/POST/DELETE methods for nuggets (still no auth though). So after this change, we have:

GET api/v0/user/1/nuggets/  - which will get all nuggets for a user
PUT api/v0/user/1/nuggets/  - which will add new nuggets for a user (the nugget data will be part of the body of the request)
POST api/v0/user/1/nuggets/1  - which will update a single nugget's text
DELETE api/v0/user/1/nuggets/1  - which will delete a single nugget

Please let me know what you think!

### CODE REVIEW

**Comment by nathanwchan** [comment]
Hey should the PUT and POST methods be swapped?  I think by definition PUTs are idempotent and typically updates a resource, whereas POSTs are not idempotent and typically creates a new resource.
Less critical, but I think the methods `nuggets_for_user` and `nuggets_by_user_and_nugget` need some renaming-love to reflect what they do.  Eg. felt a bit unnatural to call a method named `nuggets_for_user` when creating a new nugget.  Again not super critical since it's not user-facing.
Otherwise, all else looks great and this really coming along!

**Comment by karkum** [comment]
@nathanwchan yeah I screwed those up, I'll switch POST/PUT around. 

What do you think about changing it to `nugget_op_by_user` and `nugget_op_by_user_and_nugget`?

**Comment by karkum** [comment]
@nathanwchan updated

**Comment by karkum** [comment]
Congratulations @nathanwchan!!!

**Comment by nathanwchan** [comment]
thanks dude!

**Comment by nathanwchan** [comment]
This overall looks great!  Only thing I can think of is we should probably start validating nugget text length on the backend (at some point).  It's not super critical since our own clients are the only ones calling these APIs for now, and we are/will be enforcing 200-char limits in those clients (today: chrome extension does this), but still a nice safe-guard to avoid value-too-long errors enforced by Postgres/Django model constraints.

**Comment by nathanwchan** [comment]
I suppose what I mean by "safe-guard" is to gracefully return an appropriate HTTP error code so the client(s) know how to appropriately handle when text is too long in the POST/PUT (create new / update nugget) methods.

**Comment by karkum** [comment]
@nathanwchan that's a good idea, I've added guards to the serializer. Also, I fixed a problem with PUT and added a way to GET a single nugget for a single user

**Comment by karkum** [comment]
@nathanwchan can you please review/merge this?

**Comment by nathanwchan** [comment]
done!

**Pull request merged**
